# Pre-commit
# https://github.com/pre-commit/pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.174
    hooks:
      - id: checkov
        verbose: true
        args:
          - --skip-check
          - "CKV_TF_1"
          - --download-external-modules=true
          - --quiet
