name: Actions Permissions Advisor

permissions:
  actions: read

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'Number of previous runs to analyze'
        required: false
        type: number
        default: 10

jobs:
  action-permissions:
    name: Action permissions
    runs-on: ubuntu-latest
    steps:
    - name: Advisor
      uses: GitHubSecurityLab/actions-permissions/advisor@v1.0.0
      with:
        name: ${{ inputs.name }}
        count: ${{ inputs.count }}
