name: Add To GitHub Project

on:
  workflow_call:
    inputs:
      project_id:
        description: Project ID found in the URL
        required: true
        type: number

    secrets:
      add_to_project_pat:
        description: The GitHub token with access to the project
        required: true

permissions: {}

jobs:
  add-to-project:
    name: Add to GitHub projects
    runs-on: ubuntu-latest

    steps:
      # Add To GitHub Projects
      # https://github.com/marketplace/actions/add-to-github-projects

      - name: Add to GitHub project
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/osinfra-io/projects/${{ inputs.project_id }}
          github-token: ${{ secrets.add_to_project_pat }}
