name: Add To GitHub Project Called Workflow

on:
  workflow_call:
    inputs:
      project_id:
        description: Project ID found in the URL
        required: true
        type: number

    secrets:
      add_to_project_pem:
        description: The GitHub App PEM file
        required: true

permissions: {}

jobs:
  add-to-project:
    name: Add to GitHub projects
    runs-on: ubuntu-latest
    steps:
      # Create GitHub App Token
      # https://github.com/marketplace/actions/create-github-app-token

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42
        id: app-token
        with:
          app-id: 1080775
          private-key: ${{ secrets.add_to_project_pem }}

      # Add To GitHub Projects
      # https://github.com/marketplace/actions/add-to-github-projects

      - name: Add to GitHub project
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        with:
          project-url: https://github.com/orgs/osinfra-io/projects/${{ inputs.project_id }}
          github-token: ${{ steps.app-token.outputs.token }}
