name: Dependabot

on:
  workflow_call:
    secrets:
      dependabot_token:
        description: The GitHub token with access to the repository
        required: true

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    name: Pull Request Approve and Merge
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      # Fetch Metadata from Dependabot PRs
      # https://github.com/marketplace/actions/fetch-metadata-from-dependabot-prs

      - name: Run step dependabot-metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.dependabot_token }}"

      # GitHub command line
      # https://cli.github.com

      - name: Run step gh pr review --approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.dependabot_token }}

      - name: Run step gh pr merge --auto --squash
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.dependabot_token }}
