name: Dependabot Approve and Merge

on: pull_request_target

jobs:
  dependabot:
    name: Dependabot
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/dependabot.yml@token
    secrets:
      pr_approve_and_merge_pem: ${{ secrets.PR_APPROVE_AND_MERGE_PEM }}
