name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    uses: osinfra-io/github-misc-called-workflows/.github/workflows/release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
