name: Release Called Workflow

on:
  push:
    tags:
      - "v*"
  workflow_call:
    secrets:
      token:
        description: The GitHub token
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release view $TAG --repo "${{ github.repository }}" > /dev/null 2>&1 && exit 0
          gh release create $TAG \
            --repo "${{ github.repository }}" \
            --title "$TAG" \
            --generate-notes
